- name: play-1 Install python3 & docker 
  hosts: all
  become: yes
  tasks: 
  - name: play-1--task-1 install docker 
    vars:
      ansible_python_interpreter: /usr/bin/python
    yum:
      name:
      - python
      - python3
      - pip
      - docker
      update_cache: yes
      state: present
  - name: Install docker-compose
    vars:
      ansible_python_interpreter: /usr/bin/python
    get_url: 
      url: https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-linux-x86_64 
      dest: /usr/local/bin/docker-compose
      mode: +x
  - name: start & enable docker.service 
    systemd: 
      name: docker 
      state: started
      enabled: true
  - name: Add ec2-user to docker group
    user: 
      name: ec2-user
      groups: docker 
      append: yes
  - name: Reconnect to server session
    meta: reset_connection
  - name: Copy docker compose file 
    copy:
      src: /home/ahmed/Desktop/terraform/grad-proj-terraform-loadbalancer/ec2-docker/docker-compose-gp.yaml
      dest: /home/ec2-user/docker-compose.yaml
  - name: Create /var/www/html/network directory if it does not exist
    ansible.builtin.file:
      path: /var/www/html/network
      state: directory
      # mode: '0755'      
  - name: Copy network file 
    copy:
      src:  /var/www/html/index.html
      dest: /var/www/html/network/index.html
      remote_src: yes      

# To make pip install ==> you must be not root man

- name: Test docker pull
  hosts: all
  tasks:
  - name: Install docker python3 module
    vars:
      ansible_python_interpreter: /usr/bin/python3
    pip: 
      name: 
      - docker
      - docker-compose
  - name: Install docker python2 module
    vars:
      ansible_python_interpreter: /usr/bin/python
    pip: 
      name: 
      - docker==4.4.4         
      - docker-compose
  - name: docker loggin
    vars:
      ansible_python_interpreter: /usr/bin/python
    docker_login:
      registry_url: https://index.docker.io/v1/
      username: 9529777
      password: ahmed@12345  
  - name: Start docker container from docker-compose
    vars:
      ansible_python_interpreter: /usr/bin/python  
    docker_compose: 
      project_src: /home/ec2-user
      state: present        # docker-compose up
      #state: absent        # docker-compose down

    